[phases.setup]
nixPkgs = ["cmake", "gcc", "python311", "python311Packages.pip", "libstdcxx5"]

[phases.install]
cmds = [
  "pip install dlib==19.24.2",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --timeout 300 --workers 1 --threads 4"
